Neo4j seems not to install with Python 3.12 (latest) because of:
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'

So solution is to downgrade to 3.11.  To do that on heroku you put `python-3.11.8` in runtime.txt in the project root dir.